import * as css from '../views/static/css.js';
import * as databaseHelpers from '../helpers/databaseHelpers.js';

export function page404(message: string) {
    return boiler(/*HTML*/`
        <h1>Error 404:</h1>
        <p>${message}</p>
    `);
}

// HTML boilerplate
export function boiler(body: string, script?: string, head?: string) {
    return /*HTML*/`
        <!DOCTYPE html>

        <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Boilerplater</title>
                <style>${ css.webviewCss }</style>

                <script>
                    const vscode = acquireVsCodeApi();
                ${script ?? ''}
                </script>

                ${head ?? ''}
            </head>
            <body>
                ${body}
            </body>
        </html>
    `;
}

export function getInstanceContent(model: string, instance: any, db: any) {
    switch (model) {
        case ("snippets"): {
            const lang = db.getLanguage(instance);
            const tags = getTags(instance, db);
            return /*HTML*/`
                <p><strong>Title:</strong> ${instance.title}</p>
                <p><strong>Description:</strong> ${instance.description}</p>
                <p><strong>Snippet:</strong> ${instance.snippet}</p>
                <p><strong>Language:</strong> ${lang}</p>
                <p><strong>Tags:</strong> ${tags}</p>
            `;
        }
        case ("tags"): {
            return /*HTML*/`
                <p><strong>Label:</strong> ${instance.label}</p>
            `;
        }
        case ("languages"): {
            return /*HTML*/`
                <p><strong>Display name:</strong> ${instance.displayName}</p>
                <p><strong>Internal name:</strong> ${instance.internalName}</p>
            `;
        }
        default: {
            return /*HTML*/`
                <p><strong>INVALID MODEL</strong></p>
            `;
        }
    }
}

export function getEditableFields(model: string, object: any, language: any = undefined, tags: any = undefined) {
    switch (model) {
        case ("snippets"): {
            let languageOption: string;

            // Avoid "accessing property of undefined" error
            if (language && language.id && language.displayName) {
                languageOption = /*HTML*/`<option value="${language.id}" selected>${language.displayName}</option>`
            } else {
                languageOption = ''
            }

            let tagOptions = '';

            if (tags)  {
                tags.forEach((element: any) => {
                    tagOptions += /*HTML*/`<option value="${element.id}" selected>${element.label}</option>\n`;
                });
            }

            return /*HTML*/`
                <label>
                    <h2>Title:</h2>
                    <input type="text" name="title" value="${object.title || ''}" placeholder="My amazing snippet" required>
                </label>
                <label>
                    <h2>Description:</h2>
                    <textarea name="description">${object.description || ''}</textarea>
                </label>
                <label>
                    <h2>Snippet:</h2>
                    <textarea name="snippet" required>${object.snippet || ''}</textarea>
                </label>
                <div>
                    <label for="tagSelector">Tags</label>
                    <select id="tagSelector" name="tags" multiple>
                        ${tagOptions}
                    </select>
                </div>
                <div>
                    <label for="languageSelector">Language</label>
                    <select id="languageSelector" name="language" required>
                        ${languageOption}
                    </select>
                </div>
            `;
        }
        case ("languages"): {
            return page404(`Languages are automatically generated by the system and cannot be created`);
        }
        case ("tags"): {
            return /*HTML*/`
                <label>
                    <h2>Label:</h2>
                    <input type="text" name="label" value="${object.label || ''}" placeholder="Cool Functions" required>
                </label>
            `;
        }
        default: {
            return /*HTML*/`<h1>INVALID MODEL</h1>`
        }
    }
}

function getTags(instance: any, db: any): string {
    // Limit the number of tags displayed to avoid cluttering the UI
    const quantity = 5;

    // Get the tags associated with the snippet from the database
    const tags = db.query(/*SQL*/`
        SELECT t.*
        FROM tags as t
        INNER JOIN snippet_tags AS st
            ON t.id = st.tag_id
        WHERE st.snippet_id = ?
        ORDER BY t.label ASC
    `, [instance.id]) || [];

    // If there are no tags, return "None"
    if (!tags || tags.length === 0 || !tags[0].columns || !tags[0].values) {
        return 'None';
    }

    // Html string to hold the tags
    let htmlTags: string = "";

    // Loop through the tags and add them to the htmlTags string, limiting the number of tags displayed to the quantity variable
    for (let i = 0; i < tags.length; i++) {
        // Get each tag from the tags array
        const rawTag = tags[i];
        const tag = databaseHelpers.formatRows(rawTag.columns, rawTag.values)[0];
        
        // Limit the length of the tag label to avoid cluttering the UI
        const maxSize = 20;
        if (tag.label.length > maxSize) {
            tag.label = tag.label.substring(0, maxSize) + '...';
        }

        // If the current index is equal to the quantity variable, add a "more" tag to the htmlTags string and break the loop
        if (i === quantity) {
            htmlTags += /*HTML*/`<span class="tag">+${tags.length - quantity} more</span>`;
            break;
        }

        // Add the tag to the htmlTags string
        htmlTags += /*HTML*/`<span class="tag">${tag.label}</span>`
    }
    return htmlTags;
}