import * as htmlHelpers from '../../helpers/htmlHelpers.js'
import * as scripts from '../static/scripts.js'
import * as css from "../static/css.js";
import * as vscode from 'vscode';

// Page to return an HTML plain string to pass to the webView
export function index() {
    return htmlHelpers.boiler(/*HTML*/`
        <h1>Br-Zueira's Boilerplater!</h1>

        <button id="snippetBtn" onclick="goToManager('snippets')">Manage snippets</button>
        <button id="tagBtn" onclick="goToManager('tags')">Manage tags</button>
        <button id="langBtn" onclick="goToManager('languages')">Manage languages</button>
    `, scripts.index());
}

// Page to return generic list
export function list(model: string, data: any, page: number = 1, totalPages: number, db: any, isSearch: boolean = false, query: string = "") {
    // Mounting the object list
    let list = "";

    // String formating
    const modelSingular = model.slice(0, -1);
    const modelFirstUpper = model.charAt(0).toUpperCase() + model.slice(1);

    if (data) {
        // If data is found, display it in a list
        list = /*HTML*/`<ul>`;

        // Loop through the data and display each instance in a list item
        for (const instance of data) {
            // Get the instance content using the helper function
            list += /*HTML*/`<div>`;
                list += htmlHelpers.getInstanceContent(model, instance, db);
                list += /*HTML*/`<button onclick="goToEdit(${instance.id})">Edit ${modelSingular}</button>`
            list += /*HTML*/`</div>`;
        }
        list += /*HTML*/`</ul>`
    } else {
        // if no data is found, display a message to the user
        list = /*HTML*/`<p>Sorry, nothing found</p>`;
    }

    let buttons = "";

    if (page > 1) {
        buttons += /*HTML*/`<button id="lastPage" onclick="goToPage(${page - 1})">Last Page</button>`;
    }
    if (page < totalPages) {
        buttons += /*HTML*/`<button id="nextPage" onclick="goToPage(${page + 1})">Next Page</button>`;
    }

    // Dynamic footbar based on whether the user is searching or not
    let footbar = "";
    if (isSearch) { 
        footbar = /*HTML*/`
            <div id="footbar">
                <p>Search results for "${query}"</p>
            </div>
        `;
    } else { 
        footbar = /*HTML*/`
            <div id="footbar">
                <p>Page ${page} of ${totalPages}</p>
                ${buttons}
            </div>
        `;
    }
    
    // Blocks user from creating languages, since they are automatically generated by the system
    const createNew = model !== "languages" ? /*HTML*/`<button onclick="goToAdd('${model}')">Create new ${modelSingular}</button>` : "";

    return htmlHelpers.boiler(/*HTML*/`
        <!-- Like "Snippets manager" -->
        <h1>${modelFirstUpper} manager</h1>

        <button onclick="goToIndex()">Homepage</button>

        <!-- Like "Create new snippet -->
        ${createNew}

        <input type="text" id="searchBar" placeholder="Search for a specific ${modelSingular}" value="${query}">

        <!-- Like "Snippets:" -->
        <p>${modelFirstUpper}:</p>

        <div id="listContainer">
            ${list}
        </div>

        <!-- Footbar -->
        ${footbar}
    `, scripts.list(model));
}

// Generic model editing view
export function edit(model: string, object: any, id: number, context: vscode.ExtensionContext, language: any = undefined, tags: any = undefined) {
    // Blocks user from deleting languages, since they are automatically generated by the system
    const deleteButton = model === "languages" ? "" : /*HTML*/`<button type="button" onclick="deleteModel()">Delete ${model.slice(0, -1)}</button>`;
    
    // String formating
    const modelSingular = model.slice(0, -1);

    // Return the HTML page
    return htmlHelpers.boiler(/*HTML*/`
        <!-- Like "Edit snippet" -->
        <h1>Edit ${modelSingular}</h1>

        <!-- Form to edit the model -->
        <form id="editForm">
            <!-- Hidden inputs to pass the model and id to the backend -->
            <input type="hidden" name="model" value="${model}">
            <input type="hidden" name="id" value="${id}">

            <!-- The following function will return the necessary fields for each model -->
            ${htmlHelpers.getEditableFields(model, object, language, tags)}

            <footer>
                <!-- Buttons to submit the form, cancel edition and delete the model -->
                <button type="submit">Save ${modelSingular}</button>
                <button type="button" onclick="goToManager()">Cancel edition</button>
                ${deleteButton}

                <!-- Error and success messages -->
                <p id="errorMessage" role="alert" style="color: red; display: none;"></p>
                <p id="successMessage" role="alert" style="color: green; display: none;"></p>
            </footer>
        </form>
    `, scripts.edit(model, id),
    /*HTML*/`
    <style>${ css.getTomSelectLibCss(context) }</style> 
    <style>${ css.tomSelectCssOverride }</style>
    <script>${ scripts.getTomSelectLibJs(context) }</script>
    `);
}

export function add(model: string, context: vscode.ExtensionContext) {
    // String formating
    const modelSingular = model.slice(0, -1);

    // Return the HTML page
    return htmlHelpers.boiler(/*HTML*/`
        <!-- Like "Create new snippet" -->
        <h1>Create new ${modelSingular}</h1>

        <!-- Form to add the model -->
        <form id="addForm">
            <!-- Hidden input to pass the model to the backend -->
            <input type="hidden" name="model" value="${model}">

            <!-- The following function will return the necessary fields for each model -->
            ${htmlHelpers.getEditableFields(model, {}, undefined, undefined)}

            <!-- Buttons to submit the form and cancel creation -->
            <button type="submit">Create ${modelSingular}</button>
            <button type="button" onclick="goToIndex()">Cancel creation</button>

            <!-- Error and success messages -->
            <p id="errorMessage" role="alert" style="color: red; display: none;"></p>
            <p id="successMessage" role="alert" style="color: green; display: none;"></p>
        </form>
    `, scripts.add(model),
    /*HTML*/`
    <style>${ css.getTomSelectLibCss(context) }</style> 
    <style>${ css.tomSelectCssOverride }</style>
    <script>${ scripts.getTomSelectLibJs(context) }</script>
    `);
}